/**
 * ub_fk_presets.ts — Pre-computed FK joint angles for each UB body location.
 *
 * Generated by the multi-restart coordinate descent solver
 * (solveFKCoordinateDescent in arm_fk.ts). Each entry maps a UB code
 * to the ArmJointAngles that bring the left hand centroid closest to
 * that body point on the Mixamo avatar.
 *
 * Solver targets are offset 8 cm outward from the bone surface along
 * the approximate surface normal (Y-dampened for Head-anchored points),
 * so the hand touches the mesh surface instead of the centroid
 * penetrating through it.
 *
 * Accuracy: 49 of 52 non-arm points converge to < 6 cm of the offset target.
 * Outliers (Vx, Um, Gen) are physically unreachable by the left arm
 * and are excluded from the map.
 */

import type { ArmJointAngles } from "./arm_fk";

// ── Helper ──────────────────────────────────────────────────────────

/** Build an ArmJointAngles from a compact 9-tuple. */
function a(
  shoulderSwing: number, shoulderElev: number, elbowFlex: number,
  shoulderTwist: number, clavShrug: number, clavProtract: number,
  forearmTwist: number, wristFlex: number, wristDeviation: number,
): ArmJointAngles {
  return {
    clavShrug, clavProtract,
    shoulderSwing, shoulderElev, shoulderTwist,
    elbowFlex, forearmTwist,
    wristFlex, wristDeviation,
  };
}

// ── Preset map ──────────────────────────────────────────────────────

/**
 * Map from UB code → pre-computed FK angles for the left arm.
 *
 * Codes with distance > 8 cm from offset target (unreachable) are
 * deliberately omitted; callers should fall back to IK or poseArmDown
 * for missing codes.
 */
export const UB_FK_PRESETS: Readonly<Record<string, ArmJointAngles>> = {
  // ── CABEZA (Head) ─────────────────────────────────────────────────
  Ca:      a( 135, -50,  12,  -5,   1,  11,   5,  -1, -12),  // Cabeza (top)
  Par:     a( 146, -50,  47,  -5,   0,  12,   1,   3,  -3),  // Parietal
  Te:      a(  -6, -30,  64,  -3,  -5,   0,  -4, -55, -20),  // Temporal
  Au:      a(  72,  -6,  95,   4,  -5,  12,  -9, -60,  30),  // Auricular
  LobAu:   a(  63,  11, 114,   7,  -5,  12,  -9, -60,  30),  // Lóbulo Auricular

  // ── CARA (Face) ───────────────────────────────────────────────────
  Fa:      a( 124,   8,  56,  -1,   5,   3,   8,   8,   6),  // Facial (general)
  Fr:      a( 121, -44,   1,  -5,   1,   5,   3,   3,  -7),  // Frente
  IpsiFr:  a( 118, -50,   0,  90,   0,   0,   0,   0,   0),  // Frente Ipsilateral
  XFr:     a( 127, -44,   1, -31,   0,   7,   2,   9,   2),  // Frente Contralateral
  Ci:      a( 113,  -2,  57,  -3,   5,   7,   4,   9, -20),  // Ceja Ipsilateral
  Su:      a( 128, -39,   4,  -5,  -1,   1,   0,   0,   0),  // Superciliar
  Cin:     a( 123, -44,   0,  90,   0,   0,   0,   0,   0),  // Entrecejo

  // ── OJOS (Eyes) ───────────────────────────────────────────────────
  Oc:      a( 116,  -1,  57,  -1,   2,   5,   3,   7, -20),  // Ocular
  RapOc:   a( 118,  15,  74,   0,  13,  10,  13,  17,   4),  // Rabo del Ojo
  OrbOc:   a( 116,  -1,  57,   0,   4,  10,   7,   8,  -8),  // Órbita Ocular

  // ── NARIZ (Nose) ──────────────────────────────────────────────────
  Na:      a( 122,  27,  76,  -2,  10,   9,  11,  14,   0),  // Nariz
  Sep:     a( 117, -33,   4, -30,  -1,   0,   0,   0,   0),  // Septo
  AlNa:    a( 119,  28,  80,   0,   8,   9,  10,  13,  17),  // Ala Nasal

  // ── BOCA (Mouth) ──────────────────────────────────────────────────
  Po:      a( 110,  25,  83,   0,   8,  11,   6,  15,  20),  // Pómulo
  Ge:      a( 112,  30,  90,   0,  -2,   1,   0,  -3,  -5),  // Geniano
  Os:      a( 121,  34,  84,   0,   4,   4,   2,   8, -20),  // Oral superior
  IpsiOs:  a( 116,  37,  88,   0,   4,   3,   1,   7,  12),  // Oral superior ipsilateral
  XOs:     a( 126,  34,  79,   1,   8,   5,   3,  11,  20),  // Oral superior contralateral
  La:      a( 119,  39,  86,   0,   4,   4,   0,   5,   4),  // Labial
  Lab:     a( 124,  32,  81,  -1,   8,   5,   7,  11, -20),  // Labial (lower)
  Lin:     a( 121,  37,  88,   0,   4,   4,   1,   7,   1),  // Lingual
  Den:     a( 121,  37,  88,   0,   4,   4,   1,   7,   1),  // Dental
  Col:     a( 118,  37,  91,   0,   3,   2,   0,   8,  -2),  // Colmillo
  MedDen:  a( 121,  38,  88,   0,   5,   6,   3,   8,  -1),  // Medio Dental

  // ── CUELLO / MANDÍBULA (Neck / Jaw) ───────────────────────────────
  Me:      a( 130,  45,  91,   5,  -3,   0,   0,  -5,   3),  // Mentón
  Ce:      a(  33, -45, 140,   5,  -3,  11,  -8,  -8, -20),  // Cervical
  Gu:      a( 139,  87, 120,  -8,  -5,   0,   0, -33, -19),  // Gular

  // ── TORSO (Chest / Trunk) ─────────────────────────────────────────
  Co:      a( 142,  84,  97,   0,  -5,   0,   0, -60,  30),  // Cuello frontal
  IpsiCo:  a( 133, 109, 120,  -2,  -5,   0,   0, -60,  30),  // Cuello Ipsilateral
  Cla:     a( 142, 115, 130,   1,  -5,   0,   0, -33,  29),  // Clavicular
  Pe:      a( 137, 100,  89,   5,  -5,   0,   0, -60,   7),  // Pecho
  XPe:     a( 150,  97, 106,   5,  -5,   0,   0, -12,  -4),  // Pecho Contralateral
  IpsiPe:  a( 122, 121, 106,  -1,  -5,   0,   4, -60,  30),  // Pecho Ipsilateral
  Cor:     a( 150, 100, 105,  -3,  -5,   0,   6, -15, -20),  // Corazón
  Es:      a( 139, 122, 117,   0,  -5,   0,   4, -22, -10),  // Esternón
  To:      a( 137, 123, 116,  -2,  -5,   0,   4, -18, -20),  // Torso
  Cos:     a( 117, 141,  99,  -2,  -5,   0,   4, -60,  30),  // Costilla
  Dor:     a(  35, -50, 140,   5,  18,   2,   2, -18,  24),  // Dorso

  // ── ABDOMEN / CADERA (Abdomen / Hip) ──────────────────────────────
  Ve:      a( 133, 118,  93,   0,  -3,   0,   0, -10, -16),  // Vientre
  Abd:     a( 134, 117,  89,   0,  -2,   0,   0,   0,   0),  // Abdomen
  Je:      a( 121, 133, 101,   0,  -5,   0,   0,  -9,  -7),  // Jején (flank)
  Cit:     a( 122, 138,  97,   0,  -4,   0,   0,  -8,  -4),  // Cintura
  Cox:     a( 129, 137,  93,   0,  -3,   0,   1,  -7,  -3),  // Coxal

  // ── PIERNA (Leg) ──────────────────────────────────────────────────
  Fe:      a( 131,  78,   4,  -5,  -1,   0,   0,   0,   0),  // Fémur
};
