/**
 * ub_fk_presets.ts — Pre-computed FK joint angles for each UB body location.
 *
 * Generated by headless multi-restart coordinate descent solver
 * for the Lexsi avatar model (lexsi.glb on wscharacter skeleton).
 *
 * Solver targets include 8cm surface offset along approximate normal.
 * Scene auto-scale factor ~4.2x is handled by computeUBWorldPosition.
 *
 * 47/50 non-arm codes converge to < 8cm. Fe/Gen physically unreachable.
 */

import type { ArmJointAngles } from "./arm_fk";

/** Build ArmJointAngles from compact 9-tuple. */
function a(
  shoulderSwing: number, shoulderElev: number, elbowFlex: number,
  shoulderTwist: number, clavShrug: number, clavProtract: number,
  forearmTwist: number, wristFlex: number, wristDeviation: number,
): ArmJointAngles {
  return {
    clavShrug, clavProtract,
    shoulderSwing, shoulderElev, shoulderTwist,
    elbowFlex, forearmTwist,
    wristFlex, wristDeviation,
  };
}

export const UB_FK_PRESETS: Readonly<Record<string, ArmJointAngles>> = {
  // ── CABEZA (Head/Skull) ───────────────────────────────────────────
  Ca:      a(  50, -50,  89,  22,   6,   1, -80,   0,  -5),  // 1.5cm
  Vx:      a( 150, 150,  44, -41,  -4,   3,  59,  47,  30),  // 1.6cm
  Par:     a( -17,  39, 119, -62,  -5,   0,  50,  45,  -2),  // 1.1cm
  Te:      a(  56,  18, 102,  16,  -5,   0,  34,  20, -18),  // 1.5cm
  Au:      a(  -8,  51, 107,  31,   7,   0,  -5,  44, -20),  // 1.4cm
  LobAu:   a( -14,  47, 107,  22,  11,   1, -11,  56, -20),  // 1.5cm

  // ── CARA (Face) ───────────────────────────────────────────────────
  Fa:      a(  61, -50,  78,  20,  16,   0, -79,  -4, -20),  // 1.4cm
  Fr:      a(  56, -50,  89,  10,   5,   2, -80,   0,  -3),  // 1.5cm
  IpsiFr:  a(  43, -29,  72,   2,  -5,   0,  49,  60, -20),  // 1.4cm
  XFr:     a( -46, 150,   0,  36,  10,   1, -44, -51, -17),  // 1.3cm
  Ci:      a(  47, -27,  80,   6,  -5,   0,  59,  40, -20),  // 1.2cm
  Su:      a( -43, 150,   0,  39,   8,   1, -39, -49, -17),  // 1.2cm
  Cin:     a(  56, -50,  89,  15,   5,   0, -80,   0,   0),  // 1.5cm

  // ── OJOS (Eyes) ───────────────────────────────────────────────────
  Oc:      a(  61, -46,  72,   5,  -5,   1,  34,   9,  -7),  // 1.3cm
  RapOc:   a(  53, -24,  60,   5,  -5,   0,  34,  60, -20),  // 1.8cm
  OrbOc:   a(  56, -41,  74,  12,  -5,   1,  39,  15, -12),  // 1.2cm

  // ── NARIZ (Nose) ──────────────────────────────────────────────────
  Na:      a(  61, -50,  78,  20,  16,   0, -79,  -4, -20),  // 1.4cm
  Sep:     a(  61, -49,  82,  15,  15,   1, -80,  -7, -20),  // 1.5cm
  AlNa:    a(  61, -48,  70,  10,  -3,   0,  31,   5,  -4),  // 1.5cm

  // ── BOCA (Mouth) ──────────────────────────────────────────────────
  Po:      a(  61, -34,  73,   5,  -5,   0,  50,  20, -15),  // 1.5cm
  Ge:      a(  62,  -2,  98,  10,  -5,   0,  36,  11, -11),  // 1.3cm
  Os:      a(  67, -48,  77,  10,  18,   1, -80,  -7, -16),  // 2.0cm
  IpsiOs:  a(  61, -50,  74,  15,  -1,   0, -53,   0,   0),  // 1.5cm
  XOs:     a( -49, 150,   4,  45,   2,   0,   0,   0,   0),  // 1.1cm
  La:      a(  72, -50,  76,   0,  18,   2, -80, -10, -18),  // 1.4cm
  Lab:     a(  61, -50,  78,  20,  16,   1, -80,  -2, -20),  // 1.2cm
  Lin:     a(  61, -49,  83,  20,  15,   1, -80,  -3, -20),  // 1.4cm
  Den:     a(  61, -49,  83,  20,  15,   1, -80,  -3, -20),  // 1.4cm
  Col:     a(  61, -50,  78,  15,   1,   0, -56,  -3,   1),  // 1.5cm
  MedDen:  a(  67, -50,  79,  10,  17,   0, -80,  -8, -20),  // 0.9cm

  // ── CUELLO / MANDÍBULA (Neck / Jaw) ───────────────────────────────
  Me:      a(  67, -49,  77,  10,  18,   2, -79,  -8, -19),  // 1.5cm
  Ce:      a( -50, -50,  84, -64,   4,   4, -80,   4, -20),  // 1.3cm
  Gu:      a(  78, -50,  89,  15,   7,   1, -80,   0, -11),  // 1.4cm

  // ── TORSO (Chest / Trunk) ─────────────────────────────────────────
  Co:      a(  78, -50,  86,  11,  10,   0, -80,  -4, -16),  // 1.3cm
  IpsiCo:  a(  74, -29,  70,  11,  -5,   0,  26,  47, -20),  // 0.9cm
  Pe:      a(  94, -49,  80,  15,  15,   0, -80,  -6, -20),  // 1.5cm
  XPe:     a( -48, 145,   9,  21,  10,   0,  49,   6,  -6),  // 7.4cm
  IpsiPe:  a(  94, -39,  60,   5,  -5,   1,  45,  20, -19),  // 1.4cm
  Cor:     a( -49, 144,   9,  15,   9,   2,  56,   6,  -6),  // 8.1cm
  Es:      a( -50, 148,  44,  15,   0,   0,  80,  -1,   0),  // 2.2cm
  To:      a(  94, -50,  85,  15,  10,   1, -80,  -3, -17),  // 1.3cm
  Cos:     a( 118, -32,  43,   5,  -5,   0,  13,  60, -20),  // 1.3cm
  Dor:     a( -50, -49,  66, -84,   6,   6, -80,   8, -20),  // 1.3cm
  Cla:     a(  78, -50,  86,  11,  10,   0, -80,  -4, -16),  // ~Co

  // ── ABDOMEN / CADERA (Abdomen / Hip) ──────────────────────────────
  Ve:      a( -49, 138,  38,   4,   5,   0,  16,   3,  -2),  // 6.9cm
  Abd:     a( -50, 144,  44,   5,   2,   0,  73,  -2,   1),  // 4.3cm
  Je:      a( 128, -50,  47,  10,   5,   0, -80,  -3, -11),  // 2.4cm
  Cit:     a( 128, -49,  45,  10,  -4,   0,   0,   8,  -9),  // 1.4cm
  Cox:     a( 122, -49,  62,  10,  18,   6, -80,  -3, -20),  // 1.4cm
};
